### ISSUE TITLE
1-1誤植報告

### ISSUE THREAD

**Issue by Atsushi2004** [UTokyo-IPP/utokyo-ipp.github.io#2]
逆に、整数を実数に変換するには、float という関数を用います。 **int**(i) は、整数 i を実数に変換した結果を返します。 たとえば i+0.0 としても、i を実数に変換できます。

の**int**の部分が、**float**が正しいです。

**Comment by satoshigeyuki** [comment]
2022S1版において訂正されています．ご報告ありがとうございました．
