### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by gnjwj** [UTokyo-IPP/utokyo-ipp.github.io#3]
8.2 if … else による条件分岐 (pdf版でp.79)
[誤?] そして、下の2 つのプロラムの動作は明らかに異なることに注意が必要です。
[正?] そして、下の2 つのプロ[グ]ラムの動作は明らかに異なることに注意が必要です。

**Comment by satoshigeyuki** [comment]
2022A1版にて誤植を訂正しました．ご指摘ありがとうございました．
